# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  database_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssWord
      MYSQL_DATABASE: controlador_pedidos
    ports:
      - 3307:3306
    expose:
      - 3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - controladorpedidos-network
    restart: always
  
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - controladorpedidos-network
    restart: always

  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    networks:
      - controladorpedidos-network
    restart: always

  controladorpedidos:
    image: controladorpedidos
    build:
      context: .
      dockerfile: src/ControladorPedidos/Dockerfile
    ports:
      - 5003:5003
    expose:
      - 5003
    environment:
      - ConnectionStrings__DefaultConnection=server=database_mysql;database=controlador_pedidos;user=root;password=P@ssWord
      - Cache__Configuration=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
      - Aws__ServiceUrl=http://localstack:4566
      - Aws__Region=us-east-1
    networks:
      - controladorpedidos-network
    restart: on-failure
    depends_on:
      - database_mysql
      - redis
      - localstack

networks:
  controladorpedidos-network:
    driver: bridge
volumes:
  mysql_data:
    driver: local
