name: Build and Push Docker Image

on:
  pull_request:

permissions: write-all

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unit Tests
        run: dotnet test tests/ControladorPedido.Tests/ControladorPedido.Tests.csproj --collect:"XPlat Code Coverage" --settings tests/ControladorPedido.Tests/coverlet.runsettings

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "**/coverage.cobertura.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "80"

      - name: Adding Code Coverage to Summary
        run: |
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Adding Code Coverage into PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "code-coverage-results"
          recreate: true
          path: code-coverage-results.md
